/* AUTO-GENERATED by src/findings_mapper.py — do not edit by hand. */
window.SYN_FINDINGS = [
 {
  "id": "ANM-S001",
  "family": "The note doesn't match the code",
  "kind": "The note doesn't match the code",
  "category": "Cross-column",
  "nature": "Rule violation",
  "natureNote": "Near-certain data defect — the record breaks a hard rule, so no baseline is needed.",
  "signature": "Ratio / consistency break",
  "property": "Conformance",
  "flagRate": 0.365,
  "expectedMax": 0.05,
  "breached": true,
  "title": "The note doesn't match the code — 20 claims flagged",
  "summary": "20 claims where the written clinical note describes something different from what the claim is coded and billed as. Most are wellness / ambulatory / outpatient visits.",
  "what": "The written clinical note describes something different from what the claim is coded and billed as.",
  "whyFlag": "When the story in the note and the billing code disagree, one of them is probably wrong — a mis-picked code, a note attached to the wrong visit, or a template that was never updated.",
  "check": "Read the note against the code, decide which reflects what actually happened, and correct the other.",
  "measure": "Note vs. code agreement",
  "segment": "wellness · ambulatory · outpatient",
  "period": "2019-01 → 2026-05",
  "magnitude": "note and code disagree",
  "reach": "20 claims · 0.4% of all scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Suspected data issue",
  "priority": 98,
  "status": "New",
  "timing": "Newly detected",
  "signals": 20,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 66,
   "Confidence": 98,
   "Reach": 4,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 60
  },
  "why": "When the story in the note and the billing code disagree, one of them is probably wrong — a mis-picked code, a note attached to the wrong visit, or a template that was never updated.",
  "evidence": [
   {
    "claim_id": "7c50e28d-07cc-a4cf-33a5-d3f03ffc9b31",
    "cls": "wellness",
    "age": 54,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.995,
    "driver": "KNN",
    "note": "death certification; overdose (disorder)",
    "reason": "Coded as a wellness visit, but the note reads “death certification; overdose” — the note and the billing code describe different things."
   },
   {
    "claim_id": "0133267a-6406-a01b-f378-a6d7ed8ca002",
    "cls": "outpatient",
    "age": 47,
    "billed": 142.58,
    "nproc": 0,
    "score": 0.992,
    "driver": "IForest",
    "note": "consultation for treatment (procedure); sterilization requested (situation); sterilization requested (situation)",
    "reason": "Coded as an outpatient visit, but the note reads “consultation for treatment; sterilization requested; sterilization requested” — the note and the billing code describe different things."
   },
   {
    "claim_id": "5a1b2463-6dbf-ff69-2fa5-7faf6b508a37",
    "cls": "wellness",
    "age": 2,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.992,
    "driver": "IForest",
    "note": "death certification; sudden cardiac death (disorder)",
    "reason": "Coded as a wellness visit, but the note reads “death certification; sudden cardiac death” — the note and the billing code describe different things."
   },
   {
    "claim_id": "20447ad5-5095-fb78-71f1-7158d3dab345",
    "cls": "wellness",
    "age": 62,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.991,
    "driver": "KNN",
    "note": "death certification; acute st segment elevation myocardial infarction (disorder)",
    "reason": "Coded as a wellness visit, but the note reads “death certification; acute st segment elevation myocardial infarction” — the note and the billing code describe different things."
   },
   {
    "claim_id": "f9ba83f7-9940-16ae-212d-4fc422f9e7af",
    "cls": "emergency",
    "age": 48,
    "billed": 30889.76,
    "nproc": 6,
    "score": 0.989,
    "driver": "LOF",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "Coded as an emergency visit, but the note reads “encounter for check up; routine visit, no acute issues” — the note and the billing code describe different things."
   },
   {
    "claim_id": "a03e9688-2e96-60c9-58fe-7ad37ee67cc2",
    "cls": "outpatient",
    "age": 10,
    "billed": 573.98,
    "nproc": 1,
    "score": 0.989,
    "driver": "KNN",
    "note": "patient encounter procedure (procedure); plain x-ray of spine and pelvis (procedure)",
    "reason": "Coded as an outpatient visit, but the note reads “patient encounter procedure; plain x-ray of spine and pelvis” — the note and the billing code describe different things."
   },
   {
    "claim_id": "5d84e6a3-b4bd-63d6-09c6-93a22db985d5",
    "cls": "emergency",
    "age": 36,
    "billed": 26352.83,
    "nproc": 0,
    "score": 0.987,
    "driver": "LOF",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "Coded as an emergency visit, but the note reads “encounter for check up; routine visit, no acute issues” — the note and the billing code describe different things."
   },
   {
    "claim_id": "03a7cc66-36c5-356c-7080-c3d449d57edd",
    "cls": "wellness",
    "age": 74,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.986,
    "driver": "LOF",
    "note": "death certification; familial alzheimer's disease of early onset (disorder)",
    "reason": "Coded as a wellness visit, but the note reads “death certification; familial alzheimer's disease of early onset” — the note and the billing code describe different things."
   },
   {
    "claim_id": "a85e45e4-9090-0a5e-4494-c5b105225c3c",
    "cls": "outpatient",
    "age": 42,
    "billed": 36725.07,
    "nproc": 4,
    "score": 0.985,
    "driver": "KNN",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "Coded as an outpatient visit, but the note reads “encounter for check up; routine visit, no acute issues” — the note and the billing code describe different things."
   },
   {
    "claim_id": "53e4891a-9108-67ef-e1c1-a5d519fda4e1",
    "cls": "wellness",
    "age": 63,
    "billed": 860.16,
    "nproc": 0,
    "score": 0.98,
    "driver": "LOF",
    "note": "prenatal visit (regime/therapy); blighted ovum (disorder); past pregnancy history of miscarriage (situation)",
    "reason": "Coded as a wellness visit, but the note reads “prenatal visit; blighted ovum; past pregnancy history of miscarriage” — the note and the billing code describe different things."
   },
   {
    "claim_id": "6361e20a-35bf-68e3-e601-eb6d21da8e05",
    "cls": "emergency",
    "age": 24,
    "billed": 8990.49,
    "nproc": 0,
    "score": 0.98,
    "driver": "KNN",
    "note": "encounter for problem (procedure); sepsis (disorder); sepsis (disorder)",
    "reason": "Coded as an emergency visit, but the note reads “encounter for problem; sepsis; sepsis” — the note and the billing code describe different things."
   },
   {
    "claim_id": "c1e9a9fb-45ec-4ee4-d8a7-9e3e83ba4fc0",
    "cls": "wellness",
    "age": 61,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.979,
    "driver": "KNN",
    "note": "death certification; disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)",
    "reason": "Coded as a wellness visit, but the note reads “death certification; disease caused by severe acute respiratory syndrome coronavirus 2” — the note and the billing code describe different things."
   }
  ]
 },
 {
  "id": "ANM-S002",
  "family": "Procedure doesn't fit the patient's age",
  "kind": "Procedure doesn't fit the patient's age",
  "category": "Cross-column",
  "nature": "Rule violation",
  "natureNote": "Near-certain data defect — the record breaks a hard rule, so no baseline is needed.",
  "signature": "Ratio / consistency break",
  "property": "Plausibility",
  "flagRate": 0.274,
  "expectedMax": 0.05,
  "breached": true,
  "title": "Procedure doesn't fit the patient's age — 15 claims flagged",
  "summary": "15 claims where the procedure on the claim can't reasonably belong to a patient of that age. Most are wellness / outpatient / home visits.",
  "what": "The procedure on the claim can't reasonably belong to a patient of that age.",
  "whyFlag": "An adult or elderly procedure on an infant is clinically impossible — it almost always means the wrong patient, the wrong code, or a data mix-up during import, not care that was actually delivered.",
  "check": "Verify the patient's date of birth and the procedure codes against the source record.",
  "measure": "Age vs. procedure consistency",
  "segment": "wellness · outpatient · home",
  "period": "2019-01 → 2026-05",
  "magnitude": "adult surgery coded on a child aged 3 or under",
  "reach": "15 claims · 0.3% of all scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Confirmed data issue",
  "priority": 98,
  "status": "New",
  "timing": "Newly detected",
  "signals": 15,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 88,
   "Confidence": 98,
   "Reach": 3,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 92
  },
  "why": "An adult or elderly procedure on an infant is clinically impossible — it almost always means the wrong patient, the wrong code, or a data mix-up during import, not care that was actually delivered.",
  "evidence": [
   {
    "claim_id": "33d283d8-d724-4c5d-38c5-33c25a659eed",
    "cls": "home",
    "age": 1,
    "billed": 344.23,
    "nproc": 3,
    "score": 0.996,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 1, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "5e8e2a97-b1ee-6e96-2960-233f6340ebe1",
    "cls": "wellness",
    "age": 0,
    "billed": 563.08,
    "nproc": 3,
    "score": 0.983,
    "driver": "AutoEncoder",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "1e7909f8-39b2-3c7e-ddcf-bca78b4f7a96",
    "cls": "wellness",
    "age": 0,
    "billed": 1125.22,
    "nproc": 7,
    "score": 0.983,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "885c1eeb-1b4c-8a3a-7271-7c9694c7261d",
    "cls": "wellness",
    "age": 0,
    "billed": 704.2,
    "nproc": 3,
    "score": 0.981,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "373e1deb-b6b2-b528-451d-01766d352831",
    "cls": "wellness",
    "age": 2,
    "billed": 1086.18,
    "nproc": 7,
    "score": 0.98,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 2, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "9277390b-8a92-52e1-b8eb-d076c8588f89",
    "cls": "home",
    "age": 0,
    "billed": 559.93,
    "nproc": 3,
    "score": 0.98,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "5d84e6a3-b4bd-63d6-f5bf-5664d61ef215",
    "cls": "outpatient",
    "age": 0,
    "billed": 1478.85,
    "nproc": 4,
    "score": 0.979,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "688c8453-ba6f-7dec-05fd-08d682c57be0",
    "cls": "urgentcare",
    "age": 2,
    "billed": 392.8,
    "nproc": 3,
    "score": 0.979,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 2, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "311e00b9-274f-b3c6-918a-7c5db8871c3c",
    "cls": "wellness",
    "age": 1,
    "billed": 816.8,
    "nproc": 3,
    "score": 0.979,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 1, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "062ce52a-5823-aeb4-1238-8a028dda9d97",
    "cls": "wellness",
    "age": 1,
    "billed": 136.8,
    "nproc": 3,
    "score": 0.979,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 1, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "a03e9688-2e96-60c9-f3d2-f6729d3d8164",
    "cls": "wellness",
    "age": 0,
    "billed": 1326.05,
    "nproc": 5,
    "score": 0.976,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   },
   {
    "claim_id": "53e4891a-9108-67ef-e136-83ecb2041f61",
    "cls": "outpatient",
    "age": 0,
    "billed": 666.11,
    "nproc": 3,
    "score": 0.972,
    "driver": "AutoEncoder",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting",
    "reason": "Patient is age 0, but the claim lists “total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; corona…” — procedures that belong to adults, not a child this age."
   }
  ]
 },
 {
  "id": "ANM-S003",
  "family": "Doesn't look like its peers",
  "kind": "Doesn't look like its peers",
  "category": "Multivariate",
  "nature": "Outlier",
  "natureNote": "Could be legitimate — it's unusual, not impossible; confirm before treating it as a data issue.",
  "signature": "Outlier",
  "property": "Plausibility",
  "flagRate": 0.347,
  "expectedMax": 0.05,
  "breached": true,
  "title": "Doesn't look like its peers — 19 claims flagged",
  "summary": "19 claims where no single field is clearly wrong, but the whole claim is unlike any other claim of its type. Most are wellness / outpatient / emergency visits.",
  "what": "No single field is clearly wrong, but the whole claim is unlike any other claim of its type.",
  "whyFlag": "Some problems don't show up in any one field; they only stand out when you look at everything together. This is a 'something's off here' flag rather than a specific broken rule.",
  "check": "Review the claim end-to-end and treat it as a prompt to look, not a confirmed error.",
  "measure": "Overall similarity to peers",
  "segment": "wellness · outpatient · emergency",
  "period": "2019-01 → 2026-05",
  "magnitude": "unusual combination overall",
  "reach": "19 claims · 0.3% of all scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Suspected data issue",
  "priority": 98,
  "status": "New",
  "timing": "Newly detected",
  "signals": 19,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 58,
   "Confidence": 98,
   "Reach": 4,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 60
  },
  "why": "Some problems don't show up in any one field; they only stand out when you look at everything together. This is a 'something's off here' flag rather than a specific broken rule.",
  "evidence": [
   {
    "claim_id": "ba6ea998-e7a3-d122-6ad8-600a8901ca6b",
    "cls": "wellness",
    "age": 0,
    "billed": 136.8,
    "nproc": 0,
    "score": 0.99,
    "driver": "IForest",
    "note": "well child visit (procedure); aortic valve regurgitation (disorder)",
    "reason": "For a wellness visit at age 0, the note “well child visit; aortic valve regurgitation” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "9277390b-8a92-52e1-eac3-0f40da73735d",
    "cls": "inpatient",
    "age": 60,
    "billed": 29466.66,
    "nproc": 4,
    "score": 0.986,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "For an inpatient visit at age 60, an unusual combination stands out — billed $29,467 (≈5× the ~$5,424 typical for an inpatient visit); 4 procedure lines — alongside the note “encounter for check up; routine visit, no acute issues”."
   },
   {
    "claim_id": "9a57c612-581f-1c85-4f07-406b2ce2a2d5",
    "cls": "outpatient",
    "age": 35,
    "billed": 573.98,
    "nproc": 1,
    "score": 0.986,
    "driver": "LOF",
    "note": "consultation for treatment (procedure); sterilization requested (situation); sterilization requested (situation); sterilization education (p",
    "reason": "For an outpatient visit at age 35, the note “consultation for treatment; sterilization requested; sterilization requested; sterilization edu…” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "ab07c698-12cf-16d5-fdd7-fdedae4a0f01",
    "cls": "wellness",
    "age": 60,
    "billed": 25004.18,
    "nproc": 5,
    "score": 0.984,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "For a wellness visit at age 60, an unusual combination stands out — billed $25,004 (≈27× the ~$920 typical for a wellness visit); 5 procedure lines — alongside the note “encounter for check up; routine visit, no acute issues”."
   },
   {
    "claim_id": "ab07c698-12cf-16d5-d849-79db7af08fe5",
    "cls": "wellness",
    "age": 68,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.982,
    "driver": "IForest",
    "note": "death certification; chronic congestive heart failure (disorder)",
    "reason": "For a wellness visit at age 68, the note “death certification; chronic congestive heart failure” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "01a006ce-6457-50c2-b993-07cdd8028519",
    "cls": "wellness",
    "age": 56,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.98,
    "driver": "IForest",
    "note": "death certification; chronic congestive heart failure (disorder)",
    "reason": "For a wellness visit at age 56, the note “death certification; chronic congestive heart failure” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "688c8453-ba6f-7dec-55da-21b4d6f6ea82",
    "cls": "wellness",
    "age": 60,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.98,
    "driver": "IForest",
    "note": "death certification; end-stage renal disease (disorder)",
    "reason": "For a wellness visit at age 60, the note “death certification; end-stage renal disease” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "5d84e6a3-b4bd-63d6-3fbf-8c88e27a62cc",
    "cls": "outpatient",
    "age": 30,
    "billed": 1122.8,
    "nproc": 0,
    "score": 0.979,
    "driver": "IForest",
    "note": "encounter for check up (procedure); body mass index 30+ - obesity (finding)",
    "reason": "For an outpatient visit at age 30, the note “encounter for check up; body mass index 30+ - obesity” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "7ad140ab-bfae-c3ae-c90b-36fd768789a7",
    "cls": "wellness",
    "age": 70,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.979,
    "driver": "IForest",
    "note": "death certification; end-stage renal disease (disorder)",
    "reason": "For a wellness visit at age 70, the note “death certification; end-stage renal disease” is an unusual fit — no single value is wrong, but the record as a whole is unlike its peers."
   },
   {
    "claim_id": "a1733070-046a-4506-eaff-6e941a8d70ef",
    "cls": "wellness",
    "age": 38,
    "billed": 36167.0,
    "nproc": 7,
    "score": 0.976,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "For a wellness visit at age 38, an unusual combination stands out — billed $36,167 (≈39× the ~$920 typical for a wellness visit); 7 procedure lines — alongside the note “encounter for check up; routine visit, no acute issues”."
   },
   {
    "claim_id": "0fb515d6-ec2d-33f3-1d20-59c5db908fd7",
    "cls": "wellness",
    "age": 42,
    "billed": 38518.47,
    "nproc": 5,
    "score": 0.975,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "For a wellness visit at age 42, an unusual combination stands out — billed $38,518 (≈42× the ~$920 typical for a wellness visit); 5 procedure lines — alongside the note “encounter for check up; routine visit, no acute issues”."
   },
   {
    "claim_id": "688c8453-ba6f-7dec-2f07-cd16843a70f2",
    "cls": "wellness",
    "age": 53,
    "billed": 28683.41,
    "nproc": 7,
    "score": 0.973,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues",
    "reason": "For a wellness visit at age 53, an unusual combination stands out — billed $28,683 (≈31× the ~$920 typical for a wellness visit); 7 procedure lines — alongside the note “encounter for check up; routine visit, no acute issues”."
   }
  ]
 },
 {
  "id": "ANM-S004",
  "family": "Unusually large bill",
  "kind": "Unusually large bill",
  "category": "Univariate",
  "nature": "Outlier",
  "natureNote": "Could be legitimate — it's unusual, not impossible; confirm before treating it as a data issue.",
  "signature": "Outlier",
  "property": "Plausibility",
  "flagRate": 0.037,
  "expectedMax": 0.05,
  "breached": false,
  "title": "Unusually large bill — 2 claims flagged",
  "summary": "2 claims where the amount billed is far higher than similar visits normally cost. Most are emergency / urgentcare visits.",
  "what": "The amount billed is far higher than similar visits normally cost.",
  "whyFlag": "A bill many times higher than its peers is often an extra digit keyed by mistake, a duplicated charge, or a genuinely exceptional case — all worth confirming before the number is used.",
  "check": "Compare the billed amount to the procedures actually on the claim, and check for a misplaced decimal or a duplicated line.",
  "measure": "Billed amount per claim",
  "segment": "emergency · urgentcare",
  "period": "2019-01 → 2026-05",
  "magnitude": "up to 92× the typical bill",
  "reach": "2 claims · 0.0% of all scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Likely data issue",
  "priority": 97,
  "status": "New",
  "timing": "Newly detected",
  "signals": 2,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 100,
   "Confidence": 97,
   "Reach": 0,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 74
  },
  "why": "A bill many times higher than its peers is often an extra digit keyed by mistake, a duplicated charge, or a genuinely exceptional case — all worth confirming before the number is used.",
  "evidence": [
   {
    "claim_id": "20447ad5-5095-fb78-f762-d3772f8cc078",
    "cls": "emergency",
    "age": 25,
    "billed": 78624.3,
    "nproc": 0,
    "score": 0.978,
    "driver": "KNN",
    "note": "encounter for problem (procedure); sepsis (disorder); sepsis (disorder)",
    "reason": "Billed $78,624 — about 78× the typical emergency bill (around $1,009)."
   },
   {
    "claim_id": "7c50e28d-07cc-a4cf-9240-ab5439ef7ce4",
    "cls": "urgentcare",
    "age": 52,
    "billed": 86914.53,
    "nproc": 3,
    "score": 0.967,
    "driver": "KNN",
    "note": "urgent care clinic (environment); medication review due (situation); assessment of health and social care needs (procedure); depression scre",
    "reason": "Billed $86,915 — about 100× the typical urgentcare bill (around $872)."
   }
  ]
 },
 {
  "id": "ANM-S005",
  "family": "Too many procedures on one claim",
  "kind": "Too many procedures on one claim",
  "category": "Univariate",
  "nature": "Outlier",
  "natureNote": "Could be legitimate — it's unusual, not impossible; confirm before treating it as a data issue.",
  "signature": "Outlier",
  "property": "Uniqueness",
  "flagRate": 0.073,
  "expectedMax": 0.05,
  "breached": true,
  "title": "Too many procedures on one claim — 4 claims flagged",
  "summary": "4 claims where a single claim lists far more procedure lines than that kind of visit ever would. Most are wellness / ambulatory visits.",
  "what": "A single claim lists far more procedure lines than that kind of visit ever would.",
  "whyFlag": "A routine visit doesn't involve hundreds of procedures. A pile-up of line items usually means duplicated lines, several visits merged into one claim, or an export error.",
  "check": "Look for repeated identical lines and confirm the claim isn't several encounters rolled into one.",
  "measure": "Procedure lines per claim",
  "segment": "wellness · ambulatory",
  "period": "2019-01 → 2026-05",
  "magnitude": "up to 247 procedure lines on one claim",
  "reach": "4 claims · 0.1% of all scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Likely data issue",
  "priority": 97,
  "status": "New",
  "timing": "Newly detected",
  "signals": 4,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 100,
   "Confidence": 97,
   "Reach": 1,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 74
  },
  "why": "A routine visit doesn't involve hundreds of procedures. A pile-up of line items usually means duplicated lines, several visits merged into one claim, or an export error.",
  "evidence": [
   {
    "claim_id": "ad41b3b5-b5a1-f136-3c96-1b783534f27c",
    "cls": "wellness",
    "age": 37,
    "billed": 1075.86,
    "nproc": 247,
    "score": 0.973,
    "driver": "AutoEncoder",
    "note": "general examination of patient (procedure); body mass index 30+ - obesity (finding)",
    "reason": "247 procedure lines on a single wellness visit — that kind of visit normally has only a handful."
   },
   {
    "claim_id": "6c3ee07c-34a7-15d2-e2e5-a0d0d4fc3b92",
    "cls": "ambulatory",
    "age": 5,
    "billed": 85.55,
    "nproc": 185,
    "score": 0.971,
    "driver": "KNN",
    "note": "encounter for symptom (procedure); perennial allergic rhinitis with seasonal variation (disorder); perennial allergic rhinitis with seasonal",
    "reason": "185 procedure lines on a single ambulatory visit — that kind of visit normally has only a handful."
   },
   {
    "claim_id": "bf5bb016-bc49-d450-4137-d126c3d2f1b8",
    "cls": "wellness",
    "age": 16,
    "billed": 778.78,
    "nproc": 180,
    "score": 0.959,
    "driver": "AutoEncoder",
    "note": "well child visit (procedure); risk activity involvement (finding)",
    "reason": "180 procedure lines on a single wellness visit — that kind of visit normally has only a handful."
   },
   {
    "claim_id": "dbf17e44-1f14-fd36-f216-fdf625e7f406",
    "cls": "ambulatory",
    "age": 13,
    "billed": 573.98,
    "nproc": 194,
    "score": 0.959,
    "driver": "KNN",
    "note": "allergic disorder initial assessment (regime/therapy); allergic disposition (finding)",
    "reason": "194 procedure lines on a single ambulatory visit — that kind of visit normally has only a handful."
   }
  ]
 }
];
window.SYN_FAMILIES = [["Unusually large bill", "The amount billed is far higher than similar visits normally cost"], ["Too many procedures on one claim", "A single claim lists far more procedure lines than that kind of visit ever would"], ["Procedure doesn't fit the patient's age", "The procedure on the claim can't reasonably belong to a patient of that age"], ["The note doesn't match the code", "The written clinical note describes something different from what the claim is coded and billed as"], ["Doesn't look like its peers", "No single field is clearly wrong, but the whole claim is unlike any other claim of its type"]];
window.SYN_META = {
 "dataset": {
  "id": "SYN-001",
  "name": "Synthea RWD — pipeline scan",
  "vendor": "Synthea™ (MITRE) — synthetic",
  "domains": "Encounters · conditions · procedures · medications · observations",
  "obs": "1952 → 2026-07 (lifelong synthetic histories)",
  "window": "full history",
  "geo": "United States (synthetic, MA-based)",
  "cadence": "Per-encounter",
  "working": "v2026.07-syn",
  "incoming": "—",
  "latestComplete": "2026-07",
  "runout": "n/a (synthetic)",
  "dict": "Synthea CSV",
  "limits": "Fully synthetic (MITRE Synthea) — no PHI. Provider specialty uniform (general practice); note composed from encounter + linked conditions/procedures/medications."
 },
 "cohort": {
  "id": "SYN-POP",
  "name": "Full encounter population",
  "version": "v1",
  "patients": 108,
  "approval": "synthetic",
  "window": "full history"
 },
 "scan": {
  "id": "SCN-SYN-2026-07",
  "suite": "mixed-mode v1.0"
 },
 "fitness": {
  "working": "Research/demo",
  "workingNote": "synthetic data — illustrative only",
  "incoming": "—",
  "incomingRec": "—"
 },
 "summary": {
  "domains": [
   [
    "Encounters",
    "Claim unit",
    "5,473",
    "full history"
   ],
   [
    "Conditions",
    "Dx records",
    "3,784",
    "linked to encounters"
   ],
   [
    "Procedures",
    "Procedure lines",
    "15,985",
    "linked to encounters"
   ],
   [
    "Medications",
    "Med orders",
    "4,522",
    "linked to encounters"
   ],
   [
    "Observations",
    "Labs/vitals",
    "75,343",
    "linked to encounters"
   ]
  ],
  "entities": [
   [
    "Patients",
    "108"
   ],
   [
    "Providers",
    "278"
   ],
   [
    "Payers",
    "10"
   ],
   [
    "Encounter classes",
    "10"
   ]
  ],
  "completeness": [
   [
    "Encounter code",
    100.0,
    "green"
   ],
   [
    "Description",
    100.0,
    "green"
   ],
   [
    "Note composed",
    100.0,
    "green"
   ],
   [
    "Reason description",
    57.0,
    "amber"
   ],
   [
    "Total claim cost",
    100.0,
    "green"
   ]
  ],
  "fields": [
   [
    "Encounters",
    "encounter_id · class · code · desc · cost · reason",
    "structured",
    "100%"
   ],
   [
    "Conditions",
    "snomed · onset · encounter",
    "coded",
    "100%"
   ],
   [
    "Procedures",
    "snomed · base_cost · encounter",
    "coded",
    "100%"
   ],
   [
    "Medications",
    "rxnorm · dispenses · totalcost · encounter",
    "coded",
    "100%"
   ]
  ],
  "readiness": [
   [
    "Ingestion",
    "Pass",
    "18 CSV tables loaded"
   ],
   [
    "Schema validation",
    "Pass",
    "Synthea CSV export"
   ],
   [
    "Terminology mapping",
    "Pass",
    "SNOMED / RxNorm / LOINC native"
   ],
   [
    "Cohort build",
    "Pass",
    "5,473 encounters · 108 patients"
   ],
   [
    "Deduplication",
    "Pass",
    "unique encounter ids"
   ],
   [
    "Reason completeness",
    "Partial",
    "REASONDESCRIPTION 57%"
   ]
  ],
  "scanConfig": {
   "suite": "claims anomaly scan v1.0",
   "baseline": "compared within each visit type",
   "fdr": "reads the bill, the procedures, the age, and the note together"
  }
 },
 "profile": {
  "kpis": [
   [
    "5,473",
    "Encounters"
   ],
   [
    "108",
    "Patients"
   ],
   [
    "278",
    "Providers"
   ],
   [
    "100%",
    "Note completeness"
   ]
  ],
  "demo": [
   [
    "Age 45–64",
    37
   ],
   [
    "Age 18–44",
    32
   ],
   [
    "Age 0–17",
    19
   ],
   [
    "Age 65+",
    12
   ],
   [
    "Female",
    56
   ],
   [
    "Male",
    44
   ]
  ],
  "note": "The out-of-range markers relate to ANM-S001 (the unusually large bills the scan flagged). Trend is illustrative for this synthetic sample.",
  "seriesRef": "syn",
  "unit": "Flagged claims / 1,000",
  "relFinding": "ANM-S001"
 },
 "synSeries": {
  "labels": [
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   ""
  ],
  "exp": [
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0
  ],
  "lo": [
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996
  ],
  "hi": [
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999
  ],
  "obs": [
   6.1,
   5.8,
   6.2,
   5.9,
   6.0,
   6.3,
   5.7,
   6.1,
   6.0,
   6.2,
   9.4,
   12.8
  ],
  "onset": 10,
  "incompleteFrom": null
 },
 "cohortDef": {
  "incl": "All encounters in the Synthea sample; clinical note composed from encounter + linked conditions/procedures/medications.",
  "excl": "None (full population).",
  "codes": [
   "SNOMED-CT",
   "RxNorm",
   "LOINC"
  ],
  "approval": "synthetic"
 }
};
window.SYN_AUDIT = [{"ts": "2026-07-29 09:00", "act": "Scan reviewed 5,473 claims and flagged 60 that don't look right, grouped into 5 kinds of problem.", "cat": "teal", "actor": "System · claims anomaly scan"}];
window.SYN_SUMMARY = {"scanned": 5473, "flagged": 60, "findings": 5, "families": 5};
