/* AUTO-GENERATED by src/findings_mapper.py — do not edit by hand. */
window.SYN_FINDINGS = [
 {
  "id": "ANM-S001",
  "family": "Note–coding incongruence",
  "title": "Note–coding incongruence: 20 claims flagged — note↔code mismatch",
  "summary": "Unsupervised peer-group scan surfaced 20 claims exhibiting clinical note semantics inconsistent with the coded/structured claim. Concentrated in wellness · ambulatory · outpatient. Mean anomaly score 0.98; drill down to the triggering claims below.",
  "measure": "Note↔code semantic agreement",
  "segment": "wellness · ambulatory · outpatient",
  "period": "2019-01 → 2026-05",
  "magnitude": "note↔code mismatch",
  "reach": "20 claims · 0.4% of scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Suspected data issue",
  "priority": 98,
  "status": "New",
  "timing": "Newly detected",
  "signals": 20,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 66,
   "Confidence": 98,
   "Reach": 4,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 60
  },
  "why": "Peer-group ensemble ranked these claims at the top of the note–coding incongruence cluster; 20 records, reach 0.4% of the scanned population.",
  "evidence": [
   {
    "claim_id": "7c50e28d",
    "cls": "wellness",
    "age": 54,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.995,
    "driver": "KNN",
    "note": "death certification; overdose (disorder)"
   },
   {
    "claim_id": "0133267a",
    "cls": "outpatient",
    "age": 47,
    "billed": 142.58,
    "nproc": 0,
    "score": 0.992,
    "driver": "IForest",
    "note": "consultation for treatment (procedure); sterilization requested (situation); sterilization requested (situation)"
   },
   {
    "claim_id": "5a1b2463",
    "cls": "wellness",
    "age": 2,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.992,
    "driver": "IForest",
    "note": "death certification; sudden cardiac death (disorder)"
   },
   {
    "claim_id": "20447ad5",
    "cls": "wellness",
    "age": 62,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.991,
    "driver": "KNN",
    "note": "death certification; acute st segment elevation myocardial infarction (disorder)"
   },
   {
    "claim_id": "f9ba83f7",
    "cls": "emergency",
    "age": 48,
    "billed": 30889.76,
    "nproc": 6,
    "score": 0.989,
    "driver": "LOF",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "a03e9688",
    "cls": "outpatient",
    "age": 10,
    "billed": 573.98,
    "nproc": 1,
    "score": 0.989,
    "driver": "KNN",
    "note": "patient encounter procedure (procedure); plain x-ray of spine and pelvis (procedure)"
   },
   {
    "claim_id": "5d84e6a3",
    "cls": "emergency",
    "age": 36,
    "billed": 26352.83,
    "nproc": 0,
    "score": 0.987,
    "driver": "LOF",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "03a7cc66",
    "cls": "wellness",
    "age": 74,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.986,
    "driver": "LOF",
    "note": "death certification; familial alzheimer's disease of early onset (disorder)"
   },
   {
    "claim_id": "a85e45e4",
    "cls": "outpatient",
    "age": 42,
    "billed": 36725.07,
    "nproc": 4,
    "score": 0.985,
    "driver": "KNN",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "53e4891a",
    "cls": "wellness",
    "age": 63,
    "billed": 860.16,
    "nproc": 0,
    "score": 0.98,
    "driver": "LOF",
    "note": "prenatal visit (regime/therapy); blighted ovum (disorder); past pregnancy history of miscarriage (situation)"
   },
   {
    "claim_id": "6361e20a",
    "cls": "emergency",
    "age": 24,
    "billed": 8990.49,
    "nproc": 0,
    "score": 0.98,
    "driver": "KNN",
    "note": "encounter for problem (procedure); sepsis (disorder); sepsis (disorder)"
   },
   {
    "claim_id": "c1e9a9fb",
    "cls": "wellness",
    "age": 61,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.979,
    "driver": "KNN",
    "note": "death certification; disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"
   }
  ]
 },
 {
  "id": "ANM-S002",
  "family": "Demographic–clinical conflict",
  "title": "Demographic–clinical conflict: 15 claims flagged — adult/geriatric procedure on age ≤3",
  "summary": "Unsupervised peer-group scan surfaced 15 claims exhibiting patient age contradicts the documented procedure. Concentrated in wellness · outpatient · home. Mean anomaly score 0.98; drill down to the triggering claims below.",
  "measure": "Age × procedure consistency",
  "segment": "wellness · outpatient · home",
  "period": "2019-01 → 2026-05",
  "magnitude": "adult/geriatric procedure on age ≤3",
  "reach": "15 claims · 0.3% of scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Confirmed data issue",
  "priority": 98,
  "status": "New",
  "timing": "Newly detected",
  "signals": 15,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 88,
   "Confidence": 98,
   "Reach": 3,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 92
  },
  "why": "Peer-group ensemble ranked these claims at the top of the demographic–clinical conflict cluster; 15 records, reach 0.3% of the scanned population.",
  "evidence": [
   {
    "claim_id": "33d283d8",
    "cls": "home",
    "age": 1,
    "billed": 344.23,
    "nproc": 3,
    "score": 0.996,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "5e8e2a97",
    "cls": "wellness",
    "age": 0,
    "billed": 563.08,
    "nproc": 3,
    "score": 0.983,
    "driver": "AutoEncoder",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "1e7909f8",
    "cls": "wellness",
    "age": 0,
    "billed": 1125.22,
    "nproc": 7,
    "score": 0.983,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "885c1eeb",
    "cls": "wellness",
    "age": 0,
    "billed": 704.2,
    "nproc": 3,
    "score": 0.981,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "373e1deb",
    "cls": "wellness",
    "age": 2,
    "billed": 1086.18,
    "nproc": 7,
    "score": 0.98,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "9277390b",
    "cls": "home",
    "age": 0,
    "billed": 559.93,
    "nproc": 3,
    "score": 0.98,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "5d84e6a3",
    "cls": "outpatient",
    "age": 0,
    "billed": 1478.85,
    "nproc": 4,
    "score": 0.979,
    "driver": "LOF",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "688c8453",
    "cls": "urgentcare",
    "age": 2,
    "billed": 392.8,
    "nproc": 3,
    "score": 0.979,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "311e00b9",
    "cls": "wellness",
    "age": 1,
    "billed": 816.8,
    "nproc": 3,
    "score": 0.979,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "062ce52a",
    "cls": "wellness",
    "age": 1,
    "billed": 136.8,
    "nproc": 3,
    "score": 0.979,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "a03e9688",
    "cls": "wellness",
    "age": 0,
    "billed": 1326.05,
    "nproc": 5,
    "score": 0.976,
    "driver": "IForest",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   },
   {
    "claim_id": "53e4891a",
    "cls": "outpatient",
    "age": 0,
    "billed": 666.11,
    "nproc": 3,
    "score": 0.972,
    "driver": "AutoEncoder",
    "note": "total knee replacement for advanced osteoarthritis in elderly patient; hip arthroplasty; coronary artery bypass grafting"
   }
  ]
 },
 {
  "id": "ANM-S003",
  "family": "Multivariate cohort outlier",
  "title": "Multivariate cohort outlier: 19 claims flagged — peer-relative multivariate",
  "summary": "Unsupervised peer-group scan surfaced 19 claims exhibiting jointly unusual across numeric + text features vs. same-type peers. Concentrated in wellness · outpatient · emergency. Mean anomaly score 0.98; drill down to the triggering claims below.",
  "measure": "Multivariate density (peer-relative)",
  "segment": "wellness · outpatient · emergency",
  "period": "2019-01 → 2026-05",
  "magnitude": "peer-relative multivariate",
  "reach": "19 claims · 0.3% of scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Suspected data issue",
  "priority": 98,
  "status": "New",
  "timing": "Newly detected",
  "signals": 19,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 58,
   "Confidence": 98,
   "Reach": 4,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 60
  },
  "why": "Peer-group ensemble ranked these claims at the top of the multivariate cohort outlier cluster; 19 records, reach 0.3% of the scanned population.",
  "evidence": [
   {
    "claim_id": "ba6ea998",
    "cls": "wellness",
    "age": 0,
    "billed": 136.8,
    "nproc": 0,
    "score": 0.99,
    "driver": "IForest",
    "note": "well child visit (procedure); aortic valve regurgitation (disorder)"
   },
   {
    "claim_id": "9277390b",
    "cls": "inpatient",
    "age": 60,
    "billed": 29466.66,
    "nproc": 4,
    "score": 0.986,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "9a57c612",
    "cls": "outpatient",
    "age": 35,
    "billed": 573.98,
    "nproc": 1,
    "score": 0.986,
    "driver": "LOF",
    "note": "consultation for treatment (procedure); sterilization requested (situation); sterilization requested (situation); sterilization education (p"
   },
   {
    "claim_id": "ab07c698",
    "cls": "wellness",
    "age": 60,
    "billed": 25004.18,
    "nproc": 5,
    "score": 0.984,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "ab07c698",
    "cls": "wellness",
    "age": 68,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.982,
    "driver": "IForest",
    "note": "death certification; chronic congestive heart failure (disorder)"
   },
   {
    "claim_id": "01a006ce",
    "cls": "wellness",
    "age": 56,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.98,
    "driver": "IForest",
    "note": "death certification; chronic congestive heart failure (disorder)"
   },
   {
    "claim_id": "688c8453",
    "cls": "wellness",
    "age": 60,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.98,
    "driver": "IForest",
    "note": "death certification; end-stage renal disease (disorder)"
   },
   {
    "claim_id": "5d84e6a3",
    "cls": "outpatient",
    "age": 30,
    "billed": 1122.8,
    "nproc": 0,
    "score": 0.979,
    "driver": "IForest",
    "note": "encounter for check up (procedure); body mass index 30+ - obesity (finding)"
   },
   {
    "claim_id": "7ad140ab",
    "cls": "wellness",
    "age": 70,
    "billed": 211.38,
    "nproc": 0,
    "score": 0.979,
    "driver": "IForest",
    "note": "death certification; end-stage renal disease (disorder)"
   },
   {
    "claim_id": "a1733070",
    "cls": "wellness",
    "age": 38,
    "billed": 36167.0,
    "nproc": 7,
    "score": 0.976,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "0fb515d6",
    "cls": "wellness",
    "age": 42,
    "billed": 38518.47,
    "nproc": 5,
    "score": 0.975,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   },
   {
    "claim_id": "688c8453",
    "cls": "wellness",
    "age": 53,
    "billed": 28683.41,
    "nproc": 7,
    "score": 0.973,
    "driver": "IForest",
    "note": "encounter for check up (procedure); routine visit, no acute issues"
   }
  ]
 },
 {
  "id": "ANM-S004",
  "family": "Cost outlier",
  "title": "Cost outlier: 2 claims flagged — up to 92× cohort median",
  "summary": "Unsupervised peer-group scan surfaced 2 claims exhibiting billed amount far beyond peer distribution. Concentrated in emergency · urgentcare. Mean anomaly score 0.97; drill down to the triggering claims below.",
  "measure": "Billed amount per claim",
  "segment": "emergency · urgentcare",
  "period": "2019-01 → 2026-05",
  "magnitude": "up to 92× cohort median",
  "reach": "2 claims · 0.0% of scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Likely data issue",
  "priority": 97,
  "status": "New",
  "timing": "Newly detected",
  "signals": 2,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 100,
   "Confidence": 97,
   "Reach": 0,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 74
  },
  "why": "Peer-group ensemble ranked these claims at the top of the cost outlier cluster; 2 records, reach 0.0% of the scanned population.",
  "evidence": [
   {
    "claim_id": "20447ad5",
    "cls": "emergency",
    "age": 25,
    "billed": 78624.3,
    "nproc": 0,
    "score": 0.978,
    "driver": "KNN",
    "note": "encounter for problem (procedure); sepsis (disorder); sepsis (disorder)"
   },
   {
    "claim_id": "7c50e28d",
    "cls": "urgentcare",
    "age": 52,
    "billed": 86914.53,
    "nproc": 3,
    "score": 0.967,
    "driver": "KNN",
    "note": "urgent care clinic (environment); medication review due (situation); assessment of health and social care needs (procedure); depression scre"
   }
  ]
 },
 {
  "id": "ANM-S005",
  "family": "Line-item concentration",
  "title": "Line-item concentration: 4 claims flagged — up to 247 lines/claim",
  "summary": "Unsupervised peer-group scan surfaced 4 claims exhibiting implausible procedure/line-item count on a single claim. Concentrated in wellness · ambulatory. Mean anomaly score 0.97; drill down to the triggering claims below.",
  "measure": "Procedure lines per claim",
  "segment": "wellness · ambulatory",
  "period": "2019-01 → 2026-05",
  "magnitude": "up to 247 lines/claim",
  "reach": "4 claims · 0.1% of scanned",
  "confidence": "High",
  "persistence": "Point-in-time",
  "dqrisk": "Likely data issue",
  "priority": 97,
  "status": "New",
  "timing": "Newly detected",
  "signals": 4,
  "dqi": true,
  "developed": false,
  "score": {
   "Magnitude": 100,
   "Confidence": 97,
   "Reach": 1,
   "Persistence": 38,
   "Recency": 86,
   "Data-quality risk": 74
  },
  "why": "Peer-group ensemble ranked these claims at the top of the line-item concentration cluster; 4 records, reach 0.1% of the scanned population.",
  "evidence": [
   {
    "claim_id": "ad41b3b5",
    "cls": "wellness",
    "age": 37,
    "billed": 1075.86,
    "nproc": 247,
    "score": 0.973,
    "driver": "AutoEncoder",
    "note": "general examination of patient (procedure); body mass index 30+ - obesity (finding)"
   },
   {
    "claim_id": "6c3ee07c",
    "cls": "ambulatory",
    "age": 5,
    "billed": 85.55,
    "nproc": 185,
    "score": 0.971,
    "driver": "KNN",
    "note": "encounter for symptom (procedure); perennial allergic rhinitis with seasonal variation (disorder); perennial allergic rhinitis with seasonal"
   },
   {
    "claim_id": "bf5bb016",
    "cls": "wellness",
    "age": 16,
    "billed": 778.78,
    "nproc": 180,
    "score": 0.959,
    "driver": "AutoEncoder",
    "note": "well child visit (procedure); risk activity involvement (finding)"
   },
   {
    "claim_id": "dbf17e44",
    "cls": "ambulatory",
    "age": 13,
    "billed": 573.98,
    "nproc": 194,
    "score": 0.959,
    "driver": "KNN",
    "note": "allergic disorder initial assessment (regime/therapy); allergic disposition (finding)"
   }
  ]
 }
];
window.SYN_FAMILIES = [["Cost outlier", "Billed amount far beyond peer distribution"], ["Line-item concentration", "Implausible procedure/line-item count on a single claim"], ["Demographic–clinical conflict", "Patient age contradicts the documented procedure"], ["Note–coding incongruence", "Clinical note semantics inconsistent with the coded/structured claim"], ["Multivariate cohort outlier", "Jointly unusual across numeric + text features vs. same-type peers"]];
window.SYN_META = {
 "dataset": {
  "id": "SYN-001",
  "name": "Synthea RWD — pipeline scan",
  "vendor": "Synthea™ (MITRE) — synthetic",
  "domains": "Encounters · conditions · procedures · medications · observations",
  "obs": "1952 → 2026-07 (lifelong synthetic histories)",
  "window": "full history",
  "geo": "United States (synthetic, MA-based)",
  "cadence": "Per-encounter",
  "working": "v2026.07-syn",
  "incoming": "—",
  "latestComplete": "2026-07",
  "runout": "n/a (synthetic)",
  "dict": "Synthea CSV",
  "limits": "Fully synthetic (MITRE Synthea) — no PHI. Provider specialty uniform (general practice); note composed from encounter + linked conditions/procedures/medications."
 },
 "cohort": {
  "id": "SYN-POP",
  "name": "Full encounter population",
  "version": "v1",
  "patients": 108,
  "approval": "synthetic",
  "window": "full history"
 },
 "scan": {
  "id": "SCN-SYN-2026-07",
  "suite": "mixed-mode v1.0"
 },
 "fitness": {
  "working": "Research/demo",
  "workingNote": "synthetic data — illustrative only",
  "incoming": "—",
  "incomingRec": "—"
 },
 "summary": {
  "domains": [
   [
    "Encounters",
    "Claim unit",
    "5,473",
    "full history"
   ],
   [
    "Conditions",
    "Dx records",
    "3,784",
    "linked to encounters"
   ],
   [
    "Procedures",
    "Procedure lines",
    "15,985",
    "linked to encounters"
   ],
   [
    "Medications",
    "Med orders",
    "4,522",
    "linked to encounters"
   ],
   [
    "Observations",
    "Labs/vitals",
    "75,343",
    "linked to encounters"
   ]
  ],
  "entities": [
   [
    "Patients",
    "108"
   ],
   [
    "Providers",
    "278"
   ],
   [
    "Payers",
    "10"
   ],
   [
    "Encounter classes",
    "10"
   ]
  ],
  "completeness": [
   [
    "Encounter code",
    100.0,
    "green"
   ],
   [
    "Description",
    100.0,
    "green"
   ],
   [
    "Note composed",
    100.0,
    "green"
   ],
   [
    "Reason description",
    57.0,
    "amber"
   ],
   [
    "Total claim cost",
    100.0,
    "green"
   ]
  ],
  "fields": [
   [
    "Encounters",
    "encounter_id · class · code · desc · cost · reason",
    "structured",
    "100%"
   ],
   [
    "Conditions",
    "snomed · onset · encounter",
    "coded",
    "100%"
   ],
   [
    "Procedures",
    "snomed · base_cost · encounter",
    "coded",
    "100%"
   ],
   [
    "Medications",
    "rxnorm · dispenses · totalcost · encounter",
    "coded",
    "100%"
   ]
  ],
  "readiness": [
   [
    "Ingestion",
    "Pass",
    "18 CSV tables loaded"
   ],
   [
    "Schema validation",
    "Pass",
    "Synthea CSV export"
   ],
   [
    "Terminology mapping",
    "Pass",
    "SNOMED / RxNorm / LOINC native"
   ],
   [
    "Cohort build",
    "Pass",
    "5,473 encounters · 108 patients"
   ],
   [
    "Deduplication",
    "Pass",
    "unique encounter ids"
   ],
   [
    "Reason completeness",
    "Partial",
    "REASONDESCRIPTION 57%"
   ]
  ],
  "scanConfig": {
   "suite": "mixed-mode v1.0",
   "baseline": "peer-group (per encounter class)",
   "fdr": "rank-ensemble · ClinicalBERT + IForest/LOF/KNN/AE"
  }
 },
 "profile": {
  "kpis": [
   [
    "5,473",
    "Encounters"
   ],
   [
    "108",
    "Patients"
   ],
   [
    "278",
    "Providers"
   ],
   [
    "100%",
    "Note completeness"
   ]
  ],
  "demo": [
   [
    "Age 45–64",
    37
   ],
   [
    "Age 18–44",
    32
   ],
   [
    "Age 0–17",
    19
   ],
   [
    "Age 65+",
    12
   ],
   [
    "Female",
    56
   ],
   [
    "Male",
    44
   ]
  ],
  "note": "The tail-period markers relate to ANM-S004 (cost/line-item outliers surfaced by the scan). Trend is illustrative for the synthetic scan.",
  "seriesRef": "syn",
  "unit": "Flagged claims / 1,000",
  "relFinding": "ANM-S004"
 },
 "synSeries": {
  "labels": [
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   ""
  ],
  "exp": [
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0,
   6.0
  ],
  "lo": [
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996,
   3.5999999999999996
  ],
  "hi": [
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999,
   8.399999999999999
  ],
  "obs": [
   6.1,
   5.8,
   6.2,
   5.9,
   6.0,
   6.3,
   5.7,
   6.1,
   6.0,
   6.2,
   9.4,
   12.8
  ],
  "onset": 10,
  "incompleteFrom": null
 },
 "cohortDef": {
  "incl": "All encounters in the Synthea sample; clinical note composed from encounter + linked conditions/procedures/medications.",
  "excl": "None (full population).",
  "codes": [
   "SNOMED-CT",
   "RxNorm",
   "LOINC"
  ],
  "approval": "synthetic"
 }
};
window.SYN_AUDIT = [{"ts": "2026-07-29 09:00", "act": "Unsupervised mixed-mode scan (ClinicalBERT + peer-group ensemble) over 5,473 claims consolidated 60 top-scoring records into 5 findings across 5 families.", "cat": "teal", "actor": "System · claims-anomaly-pipeline"}];
window.SYN_SUMMARY = {"scanned": 5473, "flagged": 60, "findings": 5, "families": 5};
